---
apiVersion: v1
kind: Service
metadata:
  name: ib-gateway-service
  namespace: airflow

spec:
  ports:
    - name: 4002-to-4002-tcp
      port: 4002
      protocol: TCP
      targetPort: 4002
    - name: 5901-to-5900-tcp
      port: 5901
      protocol: TCP
      targetPort: 5900
  selector:
    app: ib-gateway
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ib-gateway
  namespace: airflow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ib-gateway
  template:
    metadata:
      labels:
        app: ib-gateway

    spec:
      containers:
        - name: ib-gateway
          image: waytrade/ib-gateway:981.3j
          ports:
            - containerPort: 4002
            - containerPort: 5900
          env:
            - name: TWS_USERID
              value: interactive_brockers_username
            - name: TWS_PASSWORD
              value: interactive_brockers_password
            - name: TRADING_MODE
              value: paper
